export default [
  {
    id: 1,
    venueName: "Murcia FC Stadion",
    streetAddress: "Stadion Street 1",
    zipCode: "12345",
    city: "Murcia",
    state: "Murcia",
    country: "Spain",
    teamId: 1,
  },
  {
    id: 2,
    venueName: "Murcia FC TrainingCenter",
    streetAddress: "Stadion Street 1",
    zipCode: "12345",
    city: "Murcia",
    state: "Murcia",
    country: "Spain",
    teamId: 1,
  },
  {
    id: 3,
    venueName: "Murcia FC Office",
    streetAddress: "Organisation Street 2, 10C",
    zipCode: "12345",
    city: "Murcia",
    state: "Murcia",
    country: "Spain",
    teamId: 1,
  },
  {
    id: 4,
    venueName: "Murcia FC Rehabilitation Clinic",
    streetAddress: "Stadion Street 1",
    zipCode: "12345",
    city: "Murcia",
    state: "Murcia",
    country: "Spain",
    teamId: 1,
  },
];
