export default [
  {
    id: 1,
    venueName: "Hawkins FC Stadion",
    streetAddress: "Stadion Street 1",
    zipCode: "12051",
    city: "Berlin",
    state: "Berlin",
    country: "Germany",
    teamId: 1,
  },
  {
    id: 2,
    venueName: "Hawkins FC TrainingCenter",
    streetAddress: "Stadion Street 1",
    zipCode: "12345",
    city: "Berlin",
    state: "Berlin",
    country: "Germany",
    teamId: 1,
  },
  {
    id: 3,
    venueName: "Hawkins FC Office",
    streetAddress: "Stadion Street 1",
    zipCode: "12345",
    city: "Berlin",
    state: "Berlin",
    country: "Germany",
    teamId: 1,
  },
  {
    id: 4,
    venueName: "Hawkins FC Rehabilitation Clinic",
    streetAddress: "Stadion Street 1",
    zipCode: "12345",
    city: "Berlin",
    state: "Berlin",
    country: "Germany",
    teamId: 1,
  },
];
